spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/storage
    driverClassName: org.postgresql.Driver
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
